<a href="https://colab.research.google.com/github/Maryam-Zubair/Data-Science/blob/main/AHD.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_digits
from sklearn.neighbors import KNeighborsClassifier
import numpy as np


import pandas as pd
mydata = pd.read_csv('/content/Heart.csv')

# Instructions:
- We are trying to predict who will have AHD based on Age and MaxHAR. To do so we need to:
- Read the `Heart.csv` as a data frame and split into train and test.
- Assign the predictor and response variables.
- Fit logistic regression models and interpret results
- Compute the accuracy of the model.
- Plot the classification boundaries against the two predictors
- Fit an untuned regularized logistic regression model and compare the classification boundary

# Hints:
<a href="https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html" target="_blank">sklearn.LogisticRegression()</a> : Generates a Logistic Regression classifier

<a href="https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html#sklearn.linear_model.LogisticRegression.fit" target="_blank">sklearn.fit()</a> : Fits the model to the given data

<a href="https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html#sklearn.linear_model.LogisticRegression.predict" target="_blank">sklearn.predict()</a> : Predict using the estimated model (Logistic or knn classifiers) to perform pure classification predictions

<a href="https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html#sklearn.linear_model.LogisticRegression.predict_proba" target="_blank">sklearn.predict_proba()</a> : Predict using the estimated model (Logistic or knn classifiers) to perform probability predictions of all the classes in the response (they should add up to 1 for each observation)

<a href="https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html" target="_blank">sklearn.LogisticRegression.coef_ and .intercept_</a> : Pull off the estimated $\beta$ coefficients in a Logistic Regression model

<a href="https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html#sklearn.linear_model.LogisticRegression.score" target="_blank">sklearn.score()</a> : Accuracy classification score.

<a href="https://scikit-learn.org/stable/modules/generated/sklearn.metrics.accuracy_score.html" target="_blank">sklearn.accuracy_score()</a> : Accuracy classification score

<a href="https://matplotlib.org/3.3.2/api/_as_gen/matplotlib.pyplot.pcolormesh.html" target="_blank">matplotlib.pcolormesh()</a> : Accuracy classification score

In [ ]:
import pandas as pd
import numpy as np
import sklearn as sk
import matplotlib.pyplot as plt
%matplotlib inline

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import PolynomialFeatures

- Read the Heart.csv dataset, force the response (AHD) into a binary indicator
- Print the shape and check the data with 'describe'
- Split the data into train and test, keep a 30% ratio for the test dataset. Set the random seed to 109

In [ ]:
mydata.head()

Unnamed: 0  Age  Sex     ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  \
0           1   63    1       typical     145   233    1        2    150   
1           2   67    1  asymptomatic     160   286    0        2    108   
2           3   67    1  asymptomatic     120   229    0        2    129   
3           4   37    1    nonanginal     130   250    0        0    187   
4           5   41    0    nontypical     130   204    0        2    172   

   ExAng  Oldpeak  Slope   Ca        Thal  AHD  
0      0      2.3      3  0.0       fixed   No  
1      1      1.5      2  3.0      normal  Yes  
2      1      2.6      2  2.0  reversable  Yes  
3      0      3.5      3  0.0      normal   No  
4      0      1.4      1  0.0      normal   No

In [ ]:
mydata.shape

(303, 15)

In [ ]:
# mydata['AHD'] = mydata['AHD'].apply(lambda x: 1 if x == 'Yes' else 0)

mydata['AHD']=1*(mydata['AHD']=='Yes')

In [ ]:
mydata.shape

(303, 15)

In [ ]:
mydata.describe()

Unnamed: 0         Age         Sex      RestBP        Chol         Fbs  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean   152.000000   54.438944    0.679868  131.689769  246.693069    0.148515   
std     87.612784    9.038662    0.467299   17.599748   51.776918    0.356198   
min      1.000000   29.000000    0.000000   94.000000  126.000000    0.000000   
25%     76.500000   48.000000    0.000000  120.000000  211.000000    0.000000   
50%    152.000000   56.000000    1.000000  130.000000  241.000000    0.000000   
75%    227.500000   61.000000    1.000000  140.000000  275.000000    0.000000   
max    303.000000   77.000000    1.000000  200.000000  564.000000    1.000000   

          RestECG       MaxHR       ExAng     Oldpeak       Slope          Ca  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  299.000000   
mean     0.990099  149.607261    0.326733    1.039604    1.600660    0.672241   
std      0.994971   22.875003    0.469794    1.161075    0.616226    0.937438   
min      0.000000   71.000000    0.000000    0.000000    1.000000    0.000000   
25%      0.000000  133.500000    0.000000    0.000000    1.000000    0.000000   
50%      1.000000  153.000000    0.000000    0.800000    2.000000    0.000000   
75%      2.000000  166.000000    1.000000    1.600000    2.000000    1.000000   
max      2.000000  202.000000    1.000000    6.200000    3.000000    3.000000   

              AHD  
count  303.000000  
mean     0.458746  
std      0.499120  
min      0.000000  
25%      0.000000  
50%      0.000000  
75%      1.000000  
max      1.000000

In [ ]:
X = mydata[['Age', 'MaxHR']]
y = mydata.AHD

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, random_state=109, test_size=0.3 )

**Q1.1** Below we fit an unregularized logistic regression model (`logit1`) to predict `AHD` from `Age` and `MaxHR` in the training set.  Print out the coefficient estimates, and interpret general trends.

- Fit a logistic regression model using Age and MaxHR columns. Use a first degree polynomial transformation.
- Print the model coefficients for both variables.

In [ ]:
poly1 = PolynomialFeatures(degree=1, include_bias=False)

In [ ]:
X_train_p = poly1.fit_transform(X_train)

In [ ]:
logit1 = LogisticRegression(max_iter=5000)
logit1.fit(X_train_p, y_train)

LogisticRegression(max_iter=5000)

In [ ]:
logit1.coef_, logit1.intercept_

(array([[ 0.00225983, -0.04494668]]), array([6.3609723]))

*your interpretation here*

**Q1.1** Fit an unregularized 4th order polynomial (with interactions) logistic regression model (`logit4`) to predict `AHD` from `Age` and `MaxHR` in the training set.  Print out the coefficient estimates.

In [ ]:
poly4 = PolynomialFeatures(degree=4, include_bias=False)

In [ ]:
X_train_p4 = poly4.fit_transform(X_train)

In [ ]:
logit4 = LogisticRegression(max_iter=5000)
logit4.fit(X_train_p4, y_train)

LogisticRegression(max_iter=5000)

In [ ]:
logit4.coef_, logit4.intercept_

(array([[ 3.75648705e-10,  6.40211355e-10,  1.54758501e-08,
          2.41864332e-08,  4.05332304e-08,  4.97597102e-07,
          7.21008192e-07,  1.08474580e-06,  1.65098526e-06,
          1.16778502e-06, -1.96981495e-06,  1.16769221e-06,
         -2.99028504e-07,  1.44167777e-08]]),
 array([8.49028825e-12]))

In [ ]:
poly4.get_feature_names_out()

array(['Age', 'MaxHR', 'Age^2', 'Age MaxHR', 'MaxHR^2', 'Age^3',
       'Age^2 MaxHR', 'Age MaxHR^2', 'MaxHR^3', 'Age^4', 'Age^3 MaxHR',
       'Age^2 MaxHR^2', 'Age MaxHR^3', 'MaxHR^4'], dtype=object)

**Q1.2** Evaluate the models based on misclassification rate in both the test set.

Perform the classification predictions for the model at all values in the range of the two predictors for both `logit1` and `logit4` models.

In [ ]:
X_test_p = poly1.transform(X_test)
X_test_p4 = poly4.transform(X_test)

In [ ]:
logit1.score(X_test_p, y_test)

0.6483516483516484

In [ ]:
logit4.score(X_test_p4, y_test)

0.6813186813186813

In [ ]:
n = 100
x1 = np.linspace(np.min(X_train[['Age']]), np.max(X_train[['Age']]), n)
x2 = np.linspace(np.min(X_train[['MaxHR']]), np.max(X_train[['MaxHR']]), n)

/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py:84: FutureWarning: In a future version, DataFrame.min(axis=None) will return a scalar min over the entire DataFrame. To retain the old behavior, use 'frame.min(axis=0)' or just 'frame.min()'
  return reduction(axis=axis, out=out, **passkwargs)
/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py:84: FutureWarning: In a future version, DataFrame.max(axis=None) will return a scalar max over the entire DataFrame. To retain the old behavior, use 'frame.max(axis=0)' or just 'frame.max()'
  return reduction(axis=axis, out=out, **passkwargs)
/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py:84: FutureWarning: In a future version, DataFrame.min(axis=None) will return a scalar min over the entire DataFrame. To retain the old behavior, use 'frame.min(axis=0)' or just 'frame.min()'
  return reduction(axis=axis, out=out, **passkwargs)
/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py:84: 

In [ ]:
x1

array([[29.        ],
       [29.48484848],
       [29.96969697],
       [30.45454545],
       [30.93939394],
       [31.42424242],
       [31.90909091],
       [32.39393939],
       [32.87878788],
       [33.36363636],
       [33.84848485],
       [34.33333333],
       [34.81818182],
       [35.3030303 ],
       [35.78787879],
       [36.27272727],
       [36.75757576],
       [37.24242424],
       [37.72727273],
       [38.21212121],
       [38.6969697 ],
       [39.18181818],
       [39.66666667],
       [40.15151515],
       [40.63636364],
       [41.12121212],
       [41.60606061],
       [42.09090909],
       [42.57575758],
       [43.06060606],
       [43.54545455],
       [44.03030303],
       [44.51515152],
       [45.        ],
       [45.48484848],
       [45.96969697],
       [46.45454545],
       [46.93939394],
       [47.42424242],
       [47.90909091],
       [48.39393939],
       [48.87878788],
       [49.36363636],
       [49.84848485],
       [50.33333333],
       [50

In [ ]:
x2

array([[ 71.        ],
       [ 72.32323232],
       [ 73.64646465],
       [ 74.96969697],
       [ 76.29292929],
       [ 77.61616162],
       [ 78.93939394],
       [ 80.26262626],
       [ 81.58585859],
       [ 82.90909091],
       [ 84.23232323],
       [ 85.55555556],
       [ 86.87878788],
       [ 88.2020202 ],
       [ 89.52525253],
       [ 90.84848485],
       [ 92.17171717],
       [ 93.49494949],
       [ 94.81818182],
       [ 96.14141414],
       [ 97.46464646],
       [ 98.78787879],
       [100.11111111],
       [101.43434343],
       [102.75757576],
       [104.08080808],
       [105.4040404 ],
       [106.72727273],
       [108.05050505],
       [109.37373737],
       [110.6969697 ],
       [112.02020202],
       [113.34343434],
       [114.66666667],
       [115.98989899],
       [117.31313131],
       [118.63636364],
       [119.95959596],
       [121.28282828],
       [122.60606061],
       [123.92929293],
       [125.25252525],
       [126.57575758],
       [127

In [ ]:
x1v, x2v = np.meshgrid(x1, x2)

In [ ]:
x1v

array([[29.        , 29.48484848, 29.96969697, ..., 76.03030303,
        76.51515152, 77.        ],
       [29.        , 29.48484848, 29.96969697, ..., 76.03030303,
        76.51515152, 77.        ],
       [29.        , 29.48484848, 29.96969697, ..., 76.03030303,
        76.51515152, 77.        ],
       ...,
       [29.        , 29.48484848, 29.96969697, ..., 76.03030303,
        76.51515152, 77.        ],
       [29.        , 29.48484848, 29.96969697, ..., 76.03030303,
        76.51515152, 77.        ],
       [29.        , 29.48484848, 29.96969697, ..., 76.03030303,
        76.51515152, 77.        ]])

In [ ]:
# # (29, 71), (29, 72.3), (29, 73.64)...
# (29.48, 71)...

SyntaxError: ignored

In [ ]:
x1v.shape

(100, 100)

In [ ]:
x1v.ravel().shape

(10000,)

In [ ]:
X=np.c_[x1v.ravel(), x2v.ravel()]

In [ ]:
X.shape

(10000, 2)

In [ ]:
X[:20]

array([[29.        , 71.        ],
       [29.48484848, 71.        ],
       [29.96969697, 71.        ],
       [30.45454545, 71.        ],
       [30.93939394, 71.        ],
       [31.42424242, 71.        ],
       [31.90909091, 71.        ],
       [32.39393939, 71.        ],
       [32.87878788, 71.        ],
       [33.36363636, 71.        ],
       [33.84848485, 71.        ],
       [34.33333333, 71.        ],
       [34.81818182, 71.        ],
       [35.3030303 , 71.        ],
       [35.78787879, 71.        ],
       [36.27272727, 71.        ],
       [36.75757576, 71.        ],
       [37.24242424, 71.        ],
       [37.72727273, 71.        ],
       [38.21212121, 71.        ]])

In [ ]:
X[:100]

array([[29.        , 71.        ],
       [29.48484848, 71.        ],
       [29.96969697, 71.        ],
       [30.45454545, 71.        ],
       [30.93939394, 71.        ],
       [31.42424242, 71.        ],
       [31.90909091, 71.        ],
       [32.39393939, 71.        ],
       [32.87878788, 71.        ],
       [33.36363636, 71.        ],
       [33.84848485, 71.        ],
       [34.33333333, 71.        ],
       [34.81818182, 71.        ],
       [35.3030303 , 71.        ],
       [35.78787879, 71.        ],
       [36.27272727, 71.        ],
       [36.75757576, 71.        ],
       [37.24242424, 71.        ],
       [37.72727273, 71.        ],
       [38.21212121, 71.        ],
       [38.6969697 , 71.        ],
       [39.18181818, 71.        ],
       [39.66666667, 71.        ],
       [40.15151515, 71.        ],
       [40.63636364, 71.        ],
       [41.12121212, 71.        ],
       [41.60606061, 71.        ],
       [42.09090909, 71.        ],
       [42.57575758,

In [ ]:
Xdf=pd.DataFrame(X, columns=['Age', 'MaxHR'])

In [ ]:
Xdf.head()

Age  MaxHR
0  29.000000   71.0
1  29.484848   71.0
2  29.969697   71.0
3  30.454545   71.0
4  30.939394   71.0

In [ ]:
Xdf_p1 = poly1.transform(Xdf)
Xdf_p4 = poly4.transform(Xdf)

In [ ]:
Xdfp1 = logit1.predict(Xdf_p1)
Xdfp4 = logit4.predict(Xdf_p4)

In [ ]:
plt.pcolormash(x1v, x2v)

**Q1.3** Compare the two models above on how they create the classification boundary.  Which is more likely to be overfit?  How would regularization affect these boundaries?

*your answer here*