<a href="https://colab.research.google.com/github/Maryam-Zubair/Data-Science/blob/main/logistic_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import load_digits
from sklearn.neighbors import KNeighborsClassifier
import numpy as np


### Steps:
- Import digits data set from Scikitlearn datasets library. Use `load_digits()`. When loaded, the dataset comes with `data` and `target` values.
- Assign `data` to X and `target` to y
- Check the shape of the data
- Use `np.bincount` to print the number of uniqe elements of the target vriable `y`
- Split data into train and test datasets. Use stratification when splitting. You can set your `random_state` to `42`
- Normalize your dataset. When normalizing, simply divide your dataset by the maximum of the train dataset. To find the maximum, use `max(

In [ ]:
import pandas as pd
mydata = pd.read_csv('/content/Heart.csv')

In [ ]:
digits = load_digits()
X, y = digits.data, digits.target

In [ ]:
X.shape

(1797, 64)

In [ ]:
y.shape

(1797,)

In [ ]:
np.bincount(y)

array([178, 182, 177, 183, 181, 182, 181, 179, 174, 180])

In [ ]:
np.unique(y, return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([178, 182, 177, 183, 181, 182, 181, 179, 174, 180]))

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, random_state=42)

In [ ]:
X_train_normalized = X_train / np.max(X_train)
X_test_normalized = X_test / np.max(X_train)

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
knn = KNeighborsClassifier()
log_reg = LogisticRegression(max_iter=10000)

In [ ]:
knn.fit(X_train_normalized, y_train)
log_reg.fit(X_train_normalized, y_train)

LogisticRegression(max_iter=10000)

In [ ]:
knn.score(X_test_normalized, y_test)

0.9844444444444445

In [ ]:
log_reg.score(X_test_normalized, y_test)

0.9622222222222222

In [ ]:
from sklearn.model_selection import GridSearchCV

myparams1 = {'C':np.logspace(-3, 3, 10)}
mygrid1 = GridSearchCV(LogisticRegression(max_iter=10000), param_grid=myparams1, cv=10)
mygrid1.fit(X_train_normalized, y_train)
mygrid1.score(X_test_normalized, y_test)

GridSearchCV(cv=10, estimator=LogisticRegression(max_iter=10000),
             param_grid={'C': array([1.00000000e-03, 4.64158883e-03, 2.15443469e-02, 1.00000000e-01,
       4.64158883e-01, 2.15443469e+00, 1.00000000e+01, 4.64158883e+01,
       2.15443469e+02, 1.00000000e+03])})

In [ ]:
myparams2 = {'n_neighbors':np.arange(1, 30, 2)}
mygrid2 = GridSearchCV(KNeighborsClassifier(), param_grid=myparams2, cv=10)
mygrid2.fit(X_train_normalized, y_train)
mygrid2.score(X_test_normalized, y_test)

0.9844444444444445

In [ ]:
mygrid1.best_estimator_

LogisticRegression(C=10.0, max_iter=10000)

In [ ]:
mygrid2.best_estimator_

KNeighborsClassifier(n_neighbors=1)